# Generated by Django 5.2.11 on 2026-03-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN'),
        ),
    ]
