# Generated by Django 5.2.11 on 2026-02-23 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter')], default='EMPLOYE'),
        ),
        migrations.CreateModel(
            name='EmployeCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerficate_name', models.CharField(max_length=255)),
                ('certificate_link', models.URLField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeExtreFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fild_name', models.CharField(max_length=255)),
                ('fild_value', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_extra_field', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_link', models.URLField(blank=True, max_length=255, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_profile_image')),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employecertificates')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_profile', to=settings.AUTH_USER_MODEL)),
                ('extra_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employeextrefields')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employeportfolio')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employeresume')),
            ],
        ),
    ]
