# Generated by Django 5.2.11 on 2026-02-24 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_type_employecertificates_employeextrefields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='company_logo')),
                ('website', models.URLField()),
                ('industry', models.TextField(choices=[('IT', 'It'), ('MARKETING AGENCY', 'Marketing agency'), ('SOFTWARE DEVELOPMENT', 'Software development'), ('GRAPHIC DESIGNE AGENCY', 'Graphic designe agency'), ('...', '...')], default='...')),
                ('description', models.TextField()),
                ('location', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeextrefields',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='employeportfolio',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='employeresume',
            name='employe',
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter')])),
                ('cerficate_name', models.CharField(max_length=255)),
                ('certificate_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.certificates'),
        ),
        migrations.CreateModel(
            name='ExtreFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter')])),
                ('fild_name', models.CharField(max_length=255)),
                ('fild_value', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_extra_field', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='extra_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.extrefields'),
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter')])),
                ('portfolio_link', models.URLField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.portfolios'),
        ),
        migrations.CreateModel(
            name='Recuiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('ADMIN', 'Admin'), ('RECUITER', 'Recuiter'), ('...', '...')], default='...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_recuiter', to='user.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter')])),
                ('resume', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.resumes'),
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter')])),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecuiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recuiter_profile_photo')),
                ('summary', models.TextField()),
                ('recuiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuiter_profile', to='user.recuiter')),
                ('social_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuiter_social_links', to='user.sociallinks')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeCertificates',
        ),
        migrations.DeleteModel(
            name='EmployeExtreFields',
        ),
        migrations.DeleteModel(
            name='EmployePortfolio',
        ),
        migrations.DeleteModel(
            name='EmployeResume',
        ),
    ]
