# Generated by Django 5.2.11 on 2026-02-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_company_remove_employeextrefields_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='type',
            field=models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter'), ('ADMIN', 'Admin'), ('...', '...')]),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.certificates'),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='extra_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.extrefields'),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.portfolios'),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.resumes'),
        ),
        migrations.AlterField(
            model_name='extrefields',
            name='type',
            field=models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter'), ('ADMIN', 'Admin'), ('...', '...')]),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='type',
            field=models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter'), ('ADMIN', 'Admin'), ('...', '...')]),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='type',
            field=models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter'), ('ADMIN', 'Admin'), ('...', '...')]),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='type',
            field=models.TextField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter'), ('ADMIN', 'Admin'), ('...', '...')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('EMPLOYE', 'Employe'), ('RECUITER', 'Recuiter'), ('ADMIN', 'Admin'), ('...', '...')], default='...'),
        ),
    ]
