# Generated by Django 5.2.11 on 2026-02-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_certificates_type_alter_employeprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuiterprofile',
            name='social_links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recuiter_social_links', to='user.sociallinks'),
        ),
        migrations.AlterField(
            model_name='recuiterprofile',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
