# Generated by Django 5.2.11 on 2026-02-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_recuiterprofile_social_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuiter',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_recuiter', to='user.company'),
        ),
        migrations.AlterField(
            model_name='recuiter',
            name='role',
            field=models.TextField(choices=[('ADMIN', 'Admin'), ('RECUITER', 'Recuiter'), ('...', '...')], default='...', null=True),
        ),
    ]
