# Generated by Django 5.2.11 on 2026-03-02 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_otp_company_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='type',
        ),
        migrations.RemoveField(
            model_name='extrefields',
            name='type',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='type',
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sociallinks',
            name='type',
        ),
        migrations.CreateModel(
            name='WorkedCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('resigned_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worked_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employeprofile',
            name='worked_companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.workedcompanies'),
        ),
    ]
