# Generated by Django 5.2.11 on 2026-03-06 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_certificates_type_remove_extrefields_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeprofile',
            name='worked_companies',
        ),
        migrations.RemoveField(
            model_name='recuiter',
            name='company',
        ),
        migrations.AddField(
            model_name='employeprofile',
            name='worked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worked_companies', to='user.workedcompanies'),
        ),
        migrations.AddField(
            model_name='recuiterprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='user.workedcompanies'),
        ),
        migrations.AlterField(
            model_name='workedcompanies',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
        migrations.AlterField(
            model_name='workedcompanies',
            name='resigned_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workedcompanies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
