# Generated by Django 5.2.11 on 2026-03-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_certificates_type_remove_extrefields_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recuiter',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recuiter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recuiterprofile',
            name='recuiter',
        ),
        migrations.RemoveField(
            model_name='recuiterprofile',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='workedcompanies',
            name='user',
        ),
        migrations.AlterField(
            model_name='workedcompanies',
            name='resigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_profile_image')),
                ('phone', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('certificate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ceritficates', to='user.certificates')),
                ('extra_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_extrafields', to='user.extrefields')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio', to='user.portfolios')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_resume', to='user.resumes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workedcompanies',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worked_companies', to='user.userprofile'),
        ),
        migrations.DeleteModel(
            name='EmployeProfile',
        ),
        migrations.DeleteModel(
            name='Recuiter',
        ),
        migrations.DeleteModel(
            name='RecuiterProfile',
        ),
    ]
