# Generated by Django 5.2.11 on 2026-03-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_employeprofile_worked_companies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workedcompanies',
            name='resigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
